### ISSUE TITLE
doesn't build with python3

### ISSUE THREAD

**Issue by arekm** [ldx/python-iptables#149]
````
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    execfile("iptc/version.py")
NameError: name 'execfile' is not defined
`````

2to3 open codes it like
````
--- a/setup.py  (original)
+++ b/setup.py  (refactored)
@@ -7,7 +7,7 @@
 # make pyflakes happy
 __pkgname__ = None
 __version__ = None
-execfile("iptc/version.py")
+exec(compile(open("iptc/version.py").read(), "iptc/version.py", 'exec'))

 # build/install python-iptables
 setup(

````

but also things like
````
  File "/usr/lib64/python3.4/site-packages/iptc/ip4tc.py", line 1434
    except IPTCError, e:
                    ^
SyntaxError: invalid syntax
````

**Comment by arekm** [comment]
Ups, git version looks ok :)
