### ISSUE TITLE
set match wrong in uwsgi+ web.py

### ISSUE THREAD

**Issue by eshow101** [ldx/python-iptables#163]
I write a app.py  base on web.py. It can work good in 'python app.py', bug set match wrong in uwsgi mode.

    rule = iptc.Rule()
    rule.src = ip
    match = iptc.Match(rule, "mac")
    match.mac_source = mac
    rule.add_match(match)

Traceback (most recent call last):
  File "/lib/python2/web/application.py", line 239, in process
    return self.handle()
  File "/lib/python2/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/lib/python2/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/lib/python2/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "./app.py", line 53, in GET
    release_user("192.168.1.22", "11:22:33:44:55:66")
  File "./app.py", line 30, in release_user
    match.mac_source = mac
  File "/usr/local/lib/python2.7/dist-packages/iptc/ip4tc.py", line 451, in __setattr__
    self.parse(name.replace("_", "-"), value)
  File "/usr/local/lib/python2.7/dist-packages/iptc/ip4tc.py", line 328, in parse
    self._parse(argv, inv, entry)
  File "/usr/local/lib/python2.7/dist-packages/iptc/ip4tc.py", line 596, in _parse
    self._orig_parse, self._orig_options)
  File "/usr/local/lib/python2.7/dist-packages/iptc/xtables.py", line 738, in new
    return fn(*args)
  File "/usr/local/lib/python2.7/dist-packages/iptc/xtables.py", line 1032, in parse_match
    m.name, len(argv) > 1 and argv[1] or "", rv))
XTablesError: mac: parameter '11:22:33:44:55:66' error -2

**Comment by ldx** [comment]
Hey,

can you tell me what version of Python and python-iptables you use, and what distribution/version this runs on?

The following snippet works on my Debian laptop:

    import iptc
    
    rule = iptc.Rule()
    rule.src = "1.2.3.4"
    
    match = iptc.Match(rule, "mac")
    match.mac_source = "11:22:33:44:55:66"
    rule.add_match(match)
    
    rule.create_target("ACCEPT")
    
    table = iptc.Table("filter")
    chain = iptc.Chain(table, "INPUT")
    
    chain.insert_rule(rule)

**Comment by eshow101** [comment]
Hi
iptables v1.4.18
Python 2.7.5+
The code  works in single file such as "python app.py".
but in nginx+uwsgi+web.py ,the 'Match' be wrong.When I disable 'Match',it work right.

**Comment by ldx** [comment]
@eshow101 can you tell me how to reproduce this?

Also, do you use python-iptables from pypi or latest master from GitHub?

**Comment by ldx** [comment]
No reply, closing.

**Comment by nassimabedi** [comment]
Hi,

I have exactly this error.
I have this error when my code works with nginx but it works correct without nginx.

`comment: parameter 'this is a test comment' error -2`

here is code:

```
import iptc
rule = iptc.Rule()
rule.src = "192.168.23.76"
rule.protocol = "udp"
rule.target = rule.create_target("ACCEPT")
match = rule.create_match("comment")
match.comment = "this is a test comment"
chain = iptc.Chain(iptc.Table(iptc.Table.FILTER), "INPUT")
chain.insert_rule(rule)
```
