### ISSUE TITLE
iptc.ip4tc.IPTCError: can't initialize nat: iptables who? (do you need to insmod?)

### ISSUE THREAD

**Issue by h0tbird** [ldx/python-iptables#192]
Is this a bug? Or I am missing a kernel module?

```bash
# cat Dockerfile
FROM alpine:3.4
RUN apk add -U python python-dev py-pip gcc musl-dev iptables \
    && pip install --upgrade python-iptables

CMD ["python"]
```

```
# docker build --rm -t iptc-bug .
```

```
# docker run -it --rm --privileged iptc-bug
Python 2.7.12 (default, Jun 29 2016, 08:57:23) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import iptc
>>> table = iptc.Table(iptc.Table.NAT)
>>> table = iptc.Table6(iptc.Table.NAT)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/iptc/ip6tc.py", line 587, in __new__
    obj._init(name, autocommit)
  File "/usr/lib/python2.7/site-packages/iptc/ip6tc.py", line 604, in _init
    self.refresh()
  File "/usr/lib/python2.7/site-packages/iptc/ip4tc.py", line 1584, in refresh
    self.strerror()))
iptc.ip4tc.IPTCError: can't initialize nat: iptables who? (do you need to insmod?)
>>>
```

**Comment by jllorente** [comment]
Hi, after running
```
# ip6tables-save
```
i got all these modules loaded
``` 
ip6table_security      16384  0
ip6table_mangle        16384  0
ip6table_nat           16384  0
nf_nat_ipv6            16384  1 ip6table_nat
ip6table_raw           16384  0
ip6table_filter        16384  0
ip6_tables             28672  5 ip6table_filter,ip6table_mangle,ip6table_security,ip6table_nat,ip6table_raw
```

Can you check your output?

**Comment by h0tbird** [comment]
I don't have the `ip6` modules:

```
core@kato-1 /tmp/trash $ docker run -it --net host --rm --privileged --entrypoint /sbin/lsmod iptc-bug | grep table
iptable_filter         16384  1
iptable_nat            16384  1
nf_nat_ipv4            16384  1 iptable_nat
ip_tables              24576  2 iptable_filter,iptable_nat
```

**Comment by jllorente** [comment]
What happens if you try to modprobe them? I haven't used docker, I usually go LXC or network namespaces and it works flawlessly in that environment.

**Comment by h0tbird** [comment]
Yes, just tried and now it works:

```
core@kato-1 /tmp/trash $ sudo modprobe ip6_tables
core@kato-1 /tmp/trash $ docker run -it --net host --rm --privileged --entrypoint /sbin/lsmod iptc-bug | grep table
ip6_tables             28672  0
iptable_filter         16384  1
iptable_nat            16384  1
nf_nat_ipv4            16384  1 iptable_nat
ip_tables              24576  2 iptable_filter,iptable_nat
core@kato-1 /tmp/trash $ docker run -it --net host --rm --privileged iptc-bug
Python 2.7.12 (default, Jun 29 2016, 08:57:23)
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import iptc
>>> table = iptc.Table(iptc.Table.NAT)
>>> table = iptc.Table6(iptc.Table.NAT)
>>> quit()
```

Thank you @jllorente !
