### ISSUE TITLE
multiport invalid value

### ISSUE THREAD

**Issue by mrtwister76** [ldx/python-iptables#194]
Hi,

I'm having problems with multiport match on dports.
For example:

```
self.iptcRule = iptc.Rule()
self.iptcRule.src = self.srcIp
self.iptcRule.dst = self.dstIp
match = iptc.Match(self.iptcRule, 'multiport')
match.dports = "22,23,24"
self.iptcRule.add_match(match)
```

This always raises an exception.
Stacktrace:
```
Traceback (most recent call last):
  File "./main.py", line 309, in <module>
    main.syncRules()
  File "./main.py", line 107, in syncRules
    iptcRule = fileRule.getIptcRule()
  File "/my_scripts/firewall/classes/FileRules.py", line 191, in getIptcRule
    match.dports = "22,23,24"
  File "/usr/lib64/python2.6/site-packages/iptc/ip4tc.py", line 451, in __setattr__
    self.parse(name.replace("_", "-"), value)
  File "/usr/lib64/python2.6/site-packages/iptc/ip4tc.py", line 328, in parse
    self._parse(argv, inv, entry)
  File "/usr/lib64/python2.6/site-packages/iptc/ip4tc.py", line 596, in _parse
    self._orig_parse, self._orig_options)
  File "/usr/lib64/python2.6/site-packages/iptc/xtables.py", line 748, in new
    return fn(*args)
  File "/usr/lib64/python2.6/site-packages/iptc/xtables.py", line 1053, in parse_match
    self._parse(m, argv, invert, flags, fw, ptr)
  File "/usr/lib64/python2.6/site-packages/iptc/xtables.py", line 960, in _parse
    raise ValueError("invalid value %s" % (argv[1]))
ValueError: invalid value 22,23,24
```

I've tried a list of strings, single integers, etc., but unfortunately just can't seem to get it working :(

Any help appreciated! :)

Cheers!

**Comment by mrtwister76** [comment]
OK, my mistake.
For the benefit of others... you need to add a protocol to the rule before adding a multiport match!
