### ISSUE TITLE
Unknown xtables version 12

### ISSUE THREAD

**Issue by florencka** [ldx/python-iptables#203]
I'm getting an error with iptables 1.6 and xtables version 12 on debian testing (stretch/sid). Any chance you can update to this version? I'd really appreciate it!

**Comment by ldx** [comment]
@florencka I created a branch called `issue203`, can you build & install it and report back if it works? Thanks!

**Comment by florencka** [comment]
I guess you also need `_xtables_match_v12`. I did the same changes to the version of python-iptables I installed through pip (pointed both the match and target of v12 at v10) and it worked so far. I didn't do much testing though. Will let you know if something goes wrong along the way.

```
Traceback (most recent call last):                                                                                                                                                                                                          
  File "/home/user/repos/python-iptables/iptc/xtables.py", line 825, in _xtinit                                                                                                                                                       
    self._match_struct = getattr(thismodule, matchname)                                                                                                                                                                                     
AttributeError: module 'iptc.xtables' has no attribute '_xtables_match_v12'                                                                                                                                                                  

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/repos/python-iptables/iptc/__init__.py", line 10, in <module>
    from iptc.ip4tc import (is_table_available, Table, Chain, Rule, Match, Target,
  File "/home/user/repos/python-iptables/iptc/ip4tc.py", line 40, in <module>
    xtables(NFPROTO_IPV4)
  File "/home/user/repos/python-iptables/iptc/xtables.py", line 814, in __new__
    obj._xtinit(proto)
  File "/home/user/repos/python-iptables/iptc/xtables.py", line 829, in _xtinit
    (xtables_version))
iptc.xtables.XTablesError: unknown xtables version 12
```

**Comment by florencka** [comment]
Unfortunately it seems it doesn't work with Targets that have parameters, like DSCP. I'm trying to do the following:
```
rule = iptc.Rule()
rule.out_interface = "eth0"
rule.protocol = "icmp"
target = rule.create_target("DSCP")
```
And I'm getting:
```
  File ".../iptc/ip4tc.py", line 826, in reset
    udata_buf = (ct.c_ubyte * udata_size)()
MemoryError
```

**Comment by florencka** [comment]
Allright I got it to work. The problem is that the xtables_target structure from xtables.h changed. There is a new element just before `udata_size`:
```
	/* Translate iptables to nft */
	int (*xlate)(struct xt_xlate *xl,
		     const struct xt_xlate_tg_params *params);
```
If you add the equivalent element in python then `udata_size` value is read properly again.

**Comment by mangokingTW** [comment]
Could you upload this fixed version to Pypi?
I encounter this problem since iptables is upgraded.
Thank you a lot!

**Comment by ldx** [comment]
This took a while, sorry about that. New package is now available on PyPi.

**Comment by mangokingTW** [comment]
Thank you a lot!
