### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Rule'

### ISSUE THREAD

**Issue by polarisary** [ldx/python-iptables#233]
when i use python-iptables in Flask, it throws exception as follows,who can tell me why.thanks!
------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/flask/iptc.py", line 31, in insert_rule
    rule = iptc.Rule()
AttributeError: 'module' object has no attribute 'Rule'

**Comment by polarisary** [comment]
pass，sorry

**Comment by ldx** [comment]
@polarisary it seems your module is called `iptc` itself. Can you rename it to something else? I think python is trying to import `Rule` from your `/root/flask/iptc.py`.
