### ISSUE TITLE
Problem with ldconfig and cron

### ISSUE THREAD

**Issue by RafaQueiroz** [ldx/python-iptables#239]
I've installed the python-iptables using pip in a virtualenv and i've written a simple program that writes some rules in the iptables.  When i execute the program using the command line it works just fine, but when i try to execute in a cron job it raises the following error:

`
Traceback (most recent call last):                  
  File "garf.py", line 6, in <module>               
    import iptc                                     
  File "/home/rafael/garf/venv/lib/python3.6/site-packages/iptc/__init__.py", line 10, in <module>       
    from iptc.ip4tc import (is_table_available, Table, Chain, Rule, Match, Target, Policy, IPTCError)    
  File "/home/rafael/garf/venv/lib/python3.6/site-packages/iptc/ip4tc.py", line 13, in <module>          
    from .xtables import (XT_INV_PROTO, NFPROTO_IPV4, XTablesError, xtables,                             
  File "/home/rafael/garf/venv/lib/python3.6/site-packages/iptc/xtables.py", line 812, in <module>       
    stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True       
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__                                         
    restore_signals, start_new_session)             
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child                                  
    raise child_exception_type(errno_num, err_msg, err_filename)                                         
FileNotFoundError: [Errno 2] No such file or directory: 'ldconfig': 'ldconfig'                           
`
The cron job:
*/2 * * * * cd /home/rafael/garf/src && /home/rafael/garf/venv/bin/python garf.py

How can i solve this?

**Comment by ldx** [comment]
Can you try setting PATH in your cron job config? Something like this should work:

```
*/2 * * * * cd /home/rafael/garf/src && PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin /home/rafael/garf/venv/bin/python garf.py
```

**Comment by RafaQueiroz** [comment]
Setting the path worked.

Thanks for the help.

Your lib is helping me a lot in a project.

great work! :)
