### ISSUE TITLE
Failed to set NAT to_destination with IP address and port

### ISSUE THREAD

**Issue by minglumlu** [ldx/python-iptables#242]
Hello,
I met following error when I'm setting "to_destination" of "NAT" target. Could you please help to look at it? It works with an IP address `127.0.0.1`, but fails with a port `127.0.0.1:60443`.
```
$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import iptc
>>> rule = iptc.Rule()
>>> t = rule.create_target('DNAT')
>>> t.to_destination = "127.0.0.1"
>>> t.to_destination = "127.0.0.1:60443"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mingl/.local/lib/python3.5/site-packages/iptc/ip4tc.py", line 455, in __setattr__
    self.parse(name.replace("_", "-"), value)
  File "/home/mingl/.local/lib/python3.5/site-packages/iptc/ip4tc.py", line 332, in parse
    self._parse(argv, inv, entry)
  File "/home/mingl/.local/lib/python3.5/site-packages/iptc/ip4tc.py", line 795, in _parse
    self._orig_parse, self._orig_options)
  File "/home/mingl/.local/lib/python3.5/site-packages/iptc/xtables.py", line 869, in new
    return fn(*args)
  File "/home/mingl/.local/lib/python3.5/site-packages/iptc/xtables.py", line 1123, in parse_target
    argv[1]))
iptc.errors.XTablesError: b'DNAT': parameter error -2 (b'127.0.0.1:60443')
```

The `python-iptables`  is installed with pip on Ubuntu 16.04:
```
$ pip3 show python-iptables
Name: python-iptables
Version: 0.13.0
Summary: Python bindings for iptables
Home-page: https://github.com/ldx/python-iptables
Author: Vilmos Nebehaj
Author-email: v.nebehaj@gmail.com
License: Apache License, Version 2.0
Location: /home/mingl/.local/lib/python3.5/site-packages
Requires: 
Required-by:
```

Thanks,

Ming

**Comment by minglumlu** [comment]
Sorry for stupid question.
I should specify the protocol firstly.
